const data = [
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Perlindungan Jaminan Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Penanganan Sosial dan Fakir Miskin",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Selesai",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Selesai",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Batal",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Batal",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Rehabilitas Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Perlindungan Jaminan Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Penanganan Sosial dan Fakir Miskin",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Perlindungan Jaminan Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Penanganan Sosial dan Fakir Miskin",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Perlindungan Jaminan Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Penanganan Sosial dan Fakir Miskin",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Perlindungan Jaminan Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Penanganan Sosial dan Fakir Miskin",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Perlindungan Jaminan Sosial",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
  {
    name: "Lusia Kaparang",
    email: "lusiakaparang@gmail.com",
    phoneNumber: "081244487205",
    profession: "Petani",
    address: "Tataaran",
    division: "Penanganan Sosial dan Fakir Miskin",
    purpose: "Ini adalah tujuan",
    status: "Belum",
  },
];

// Mendapatkan tanggal saat ini
const now = new Date();

// Membuat tanggal createdAt (waktu penciptaan)
const createdAt = now.toISOString();

// Menghitung tanggal 7 hari yang lalu untuk updatedAt
const updatedAt = new Date(
  now.getTime() - 7 * 24 * 60 * 60 * 1000
).toISOString();

// Menambahkan createdAt dan updatedAt ke setiap objek dalam array data
export const dataWithTimestamps = data.map((item) => {
  return {
    ...item,
    createdAt: createdAt,
    updatedAt: updatedAt,
  };
});
